version: '2.1'
services:
  platform-configuration:
    build: bookstore-microservices-platform-configuration
    restart: always
    ports:
      - 8888:8888

  platform-registry:
    build: bookstore-microservices-platform-registry
    environment:
      CONFIG_HOST: platform-configuration
    restart: always
    depends_on:
      platform-configuration:
        condition: service_healthy
    ports:
      - 8761:8761

  platform-gateway:
    build: bookstore-microservices-platform-gateway
    depends_on:
      platform-configuration:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
    restart: always
    ports:
      - 8080:8080

  domain-security:
    build: bookstore-microservices-domain-security
    depends_on:
      platform-configuration:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
    restart: always
    ports:
      - 8301:8301

  domain-account:
    build: bookstore-microservices-domain-account
    depends_on:
      platform-configuration:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
      AUTH_HOST: domain-security
    restart: always
    ports:
      - 8401:8401

  domain-warehouse:
    build: bookstore-microservices-domain-warehouse
    depends_on:
      platform-configuration:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
      AUTH_HOST: domain-security
    restart: always
    ports:
      - 8501:8501

  domain-payment:
    build: bookstore-microservices-domain-payment
    depends_on:
      platform-configuration:
        condition: service_healthy
    environment:
      CONFIG_HOST: platform-configuration
      REGISTRY_HOST: platform-registry
      AUTH_HOST: domain-security
    restart: always
    ports:
      - 8601:8601
